/*
 * Minimal FFmpeg + SDL2 Video Player
 * Note: This code was generated by an AI language model CHATGPT.
 * Compatible with FFmpeg versions:
 *   libavcodec    58.134.100
 *   libavformat   58.76.100
 *   libavutil     56.70.100
 *   libswscale    5.9.100
 * SDL2            2.0.20
 */

#include <SDL2/SDL.h>
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>

#define SDL_AUDIO_BUFFER_SIZE 1024
#define MAX_VIDEOQ_SIZE (5 * 256 * 1024)

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <video file>\n", argv[0]);
        return -1;
    }

    av_register_all();
    avformat_network_init();

    AVFormatContext *fmt_ctx = NULL;
    if (avformat_open_input(&fmt_ctx, argv[1], NULL, NULL) != 0) {
        fprintf(stderr, "Could not open source file %s\n", argv[1]);
        return -1;
    }
    if (avformat_find_stream_info(fmt_ctx, NULL) < 0) {
        fprintf(stderr, "Could not find stream information\n");
        return -1;
    }

    int video_stream = -1;
    for (unsigned i = 0; i < fmt_ctx->nb_streams; i++) {
        if (fmt_ctx->streams[i]->codecpar->codec_type == AVMEDIA_TYPE_VIDEO) {
            video_stream = i;
            break;
        }
    }
    if (video_stream == -1) {
        fprintf(stderr, "No video stream found\n");
        return -1;
    }

    AVCodecParameters *codecpar = fmt_ctx->streams[video_stream]->codecpar;
    AVCodec *codec = avcodec_find_decoder(codecpar->codec_id);
    if (!codec) {
        fprintf(stderr, "Unsupported codec!\n");
        return -1;
    }

    AVCodecContext *codec_ctx = avcodec_alloc_context3(codec);
    avcodec_parameters_to_context(codec_ctx, codecpar);
    if (avcodec_open2(codec_ctx, codec, NULL) < 0) {
        fprintf(stderr, "Could not open codec\n");
        return -1;
    }

    AVFrame *frame = av_frame_alloc();
    AVFrame *frame_rgb = av_frame_alloc();
    int width = codec_ctx->width;
    int height = codec_ctx->height;
    struct SwsContext *sws_ctx = sws_getContext(width, height, codec_ctx->pix_fmt,
                                                width, height, AV_PIX_FMT_RGB24,
                                                SWS_BILINEAR, NULL, NULL, NULL);

    int num_bytes = av_image_get_buffer_size(AV_PIX_FMT_RGB24, width, height, 1);
    uint8_t *buffer = (uint8_t *)av_malloc(num_bytes);
    av_image_fill_arrays(frame_rgb->data, frame_rgb->linesize,
                         buffer, AV_PIX_FMT_RGB24, width, height, 1);

    SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_TIMER);
    SDL_Window *window = SDL_CreateWindow("FFmpeg SDL2 Player",
                                          SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                          width, height, 0);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
    SDL_Texture *texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_RGB24,
                                             SDL_TEXTUREACCESS_STREAMING, width, height);

    AVPacket packet;
    int quit = 0;
    SDL_Event event;

    while (!quit) {
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT) {
                quit = 1;
            }
        }

        if (av_read_frame(fmt_ctx, &packet) >= 0) {
            if (packet.stream_index == video_stream) {
                if (avcodec_send_packet(codec_ctx, &packet) >= 0) {
                    if (avcodec_receive_frame(codec_ctx, frame) == 0) {
                        sws_scale(sws_ctx, (const uint8_t * const *)frame->data, frame->linesize,
                                  0, height, frame_rgb->data, frame_rgb->linesize);

                        SDL_UpdateTexture(texture, NULL, frame_rgb->data[0], frame_rgb->linesize[0]);
                        SDL_RenderClear(renderer);
                        SDL_RenderCopy(renderer, texture, NULL, NULL);
                        SDL_RenderPresent(renderer);
                        SDL_Delay(33); // ~30 fps
                    }
                }
            }
            av_packet_unref(&packet);
        } else {
            quit = 1; // end of video
        }
    }

    av_free(buffer);
    av_frame_free(&frame);
    av_frame_free(&frame_rgb);
    avcodec_free_context(&codec_ctx);
    avformat_close_input(&fmt_ctx);

    SDL_DestroyTexture(texture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}